### ISSUE TITLE
Crash on start when updating to v2.2.X

### ISSUE THREAD

**Issue by OzGav** [mikelawrence/senseme-hacs#28]
## Describe the bug
Crashing on start

```
Logger: homeassistant.config_entries
Source: custom_components/senseme/__init__.py:40
First occurred: 2:00:29 PM (1 occurrences)
Last logged: 2:00:29 PM

Error setting up entry SenseME for senseme
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/senseme/__init__.py", line 40, in async_setup_entry
    info=entry.data[CONF_INFO], start_first=True, refresh_minutes=UPDATE_RATE
KeyError: 'info'
```

## Debug log

```text

2021-03-04 14:00:29 DEBUG (MainThread) [custom_components.senseme] Using aiosenseme library version 0.5.2
2021-03-04 14:00:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration bom_forecast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-03-04 14:00:29 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry SenseME for senseme
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/senseme/__init__.py", line 40, in async_setup_entry
info=entry.data[CONF_INFO], start_first=True, refresh_minutes=UPDATE_RATE
KeyError: 'info'

```

**Comment by mikelawrence** [comment]
You need to remove the SenseME integration from Home Assistant before adding it again. Goto **Configuration -> Integrations** click the three vertical dots on the the SenseME integration and then click **Delete**. Then re-add the SenseME integration as discussed in the Readme.

**Comment by OzGav** [comment]
Thanks Mike. Sorry for the hassle....

**Comment by mikelawrence** [comment]
There is a way to handle this programmatically I just haven't implemented it. So you reporting this error is reasonable.

I'm going to reopen this issue so others who have this problem will see the solution.
