### ISSUE TITLE
Doesn't work with python 3.11 therefore no HAOS version since 2023.6.1 

### ISSUE THREAD

**Issue by davidmankin** [mikelawrence/senseme-hacs#45]
The syntax or requirements for asyncio have changed with python 3.11, which is now the required python in today's Home Assistant OS installs. 

I still used SenseMe integration instead of migrating to Big Ass Fans because it worked great and I didn't want to touch what was working well.  Since I installed HA 2023.6.x it no longer works at all.  

Please clarify whether this is something to fix and I can wait, or if this integration is dead and I should bite the bullet and move to Big Ass Fans integration. 

## Version of the custom_component

v2.2.5

## Describe the bug

Integration crashes with this error log message:

```text
Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/senseme/__init__.py:40
Integration: SenseME ([documentation](https://www.github.com/mikelawrence/senseme-hacs), [issues](https://github.com/mikelawrence/senseme-hacs/issues))
First occurred: June 10, 2023 at 4:15:54 PM (4 occurrences)
Last logged: 8:24:33 PM

Error setting up entry David’s Office Fan for senseme
Error setting up entry Red Couch Fan for senseme
Error setting up entry Kids Room Fan for senseme
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/senseme/__init__.py", line 40, in async_setup_entry
    status, device = await async_get_device_by_device_info(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosenseme/discovery.py", line 572, in async_get_device_by_device_info
    if await device.async_update(timeout_seconds=timeout_seconds):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiosenseme/device.py", line 694, in async_update
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

``` 

## Debug log

Not relevant. 

```text

Add your logs here.

```

**Comment by claytonjn** [comment]
FWIW, I was also holding off on the firmware update due to drop of support of Sleep mode, however after the integration broke in 2023.6.x I finally went ahead with the update and the Big Ass Fans exposes a lot more functionality, so I was able to emulate the sleep mode with very trivial changes to my automations. So far I'm glad to have updated.

**Comment by davidmankin** [comment]
Thanks for sharing.  I just bit the bullet and upgraded too.  

Anyway I think we should say whether or not this integration will be updated or is EOL.

**Comment by smokey-live** [comment]
I have an older Haiku fan that will not upgrade to the BAF firmware like my newer L Series did. Hopefully this integration can be updated so that I don't loose control over my older fan.

**Comment by mikelawrence** [comment]
I no longer have access to any Big Ass Fans. Like the senseme integration in Home Assistant this integration is deprecated. Sorry.

**Comment by mercurylines** [comment]
Any recent updates or patches to this?

**Comment by nitenjaiswal** [comment]
I have older fans and (using AI) made small changes that allowed my fans to be integrated into HA.  i had it working with 2026.8.x but 2026.9.x broke it again.  I've combined all my fixes and posted a pull request.  I can confirm that HA (2026.9.1) controls the fans with no issues.
